install:
  - cinst pester

build: false

test_script:
  - ps: $resultsFile = '.\TestsResults.xml'
  - ps: $config = New-PesterConfiguration
  - ps: $config.TestResult.OutputFormat = 'NUnitXml'
  - ps: $config.TestResult.OutputPath = $resultsFile
  - ps: $config.TestResult.Enabled = $true
  - ps: $config.Run.Path = '.\PesterTests'
  - ps: $config.Run.PassThru = $true
  - ps: $res = Invoke-Pester -Configuration $config  
  - ps: $resolvedFile = (Resolve-Path $resultsFile)
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", $resolvedFile)
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}
